export const TYPE = {
  STRING: 'STRING',
  NUMERIC: 'NUMERIC',
  DATE: 'DATE',
  TIMESTAMP: 'TIMESTAMP'
};

export const COLUMN = {
  VALUE_1: 'VALUE_1',
  VALUE_3: 'VALUE_3',
  TERMINATION_DT: 'TERMINATION_DT',
  DESCRIPTION: 'DESCRIPTION',
  SOURCE_NM: 'SOURCE_NM',
  CLIENT_NM: 'CLIENT_NM',
};

export const COLOR = {
  LIGHT_BLUE: '#d8eefd',
  BLUE: '#5aa9e6',
  WHITE: '#f9f9f9',
  RED: '#f50049',
  YELLOW: '#ffe45e',
};

export const EDITABLE_FIELD_LIST = [
  'DESCRIPTION', 'SOURCE_NM', 'CLIENT_NM', 'TERMINATION_DT', 'VALUE_3'
]
